/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienciasIndexRouteImport } from './routes/experiencias/index'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasIndexRoute = ExperienciasIndexRouteImport.update({
  id: '/experiencias/',
  path: '/experiencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/experiencias/$slug',
  path: '/experiencias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/': typeof ExperienciasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias': typeof ExperienciasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/': typeof ExperienciasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experiencias/$slug' | '/experiencias/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experiencias/$slug' | '/experiencias'
  id: '__root__' | '/' | '/experiencias/$slug' | '/experiencias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
  ExperienciasIndexRoute: typeof ExperienciasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/': {
      id: '/experiencias/'
      path: '/experiencias'
      fullPath: '/experiencias/'
      preLoaderRoute: typeof ExperienciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/$slug': {
      id: '/experiencias/$slug'
      path: '/experiencias/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienciasSlugRoute: ExperienciasSlugRoute,
  ExperienciasIndexRoute: ExperienciasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
