/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminExperienciasRouteImport } from './routes/admin/experiencias'
import { Route as ExperienciasIndexRouteImport } from './routes/experiencias/index'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias/$slug'
import { Route as AdminExperienciasNovaRouteImport } from './routes/admin/experiencias/nova'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienciasRoute = AdminExperienciasRouteImport.update({
  id: '/admin/experiencias',
  path: '/admin/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasIndexRoute = ExperienciasIndexRouteImport.update({
  id: '/experiencias/',
  path: '/experiencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/experiencias/$slug',
  path: '/experiencias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExperienciasNovaRoute = AdminExperienciasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminExperienciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/experiencias': typeof AdminExperienciasRouteWithChildren
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/': typeof ExperienciasIndexRoute
  '/admin/experiencias/nova': typeof AdminExperienciasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/experiencias': typeof AdminExperienciasRouteWithChildren
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias': typeof ExperienciasIndexRoute
  '/admin/experiencias/nova': typeof AdminExperienciasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/experiencias': typeof AdminExperienciasRouteWithChildren
  '/experiencias/$slug': typeof ExperienciasSlugRoute
  '/experiencias/': typeof ExperienciasIndexRoute
  '/admin/experiencias/nova': typeof AdminExperienciasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/experiencias'
    | '/experiencias/$slug'
    | '/experiencias/'
    | '/admin/experiencias/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/experiencias'
    | '/experiencias/$slug'
    | '/experiencias'
    | '/admin/experiencias/nova'
  id:
    | '__root__'
    | '/'
    | '/admin/experiencias'
    | '/experiencias/$slug'
    | '/experiencias/'
    | '/admin/experiencias/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminExperienciasRoute: typeof AdminExperienciasRouteWithChildren
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
  ExperienciasIndexRoute: typeof ExperienciasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experiencias': {
      id: '/admin/experiencias'
      path: '/admin/experiencias'
      fullPath: '/admin/experiencias'
      preLoaderRoute: typeof AdminExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/': {
      id: '/experiencias/'
      path: '/experiencias'
      fullPath: '/experiencias/'
      preLoaderRoute: typeof ExperienciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/$slug': {
      id: '/experiencias/$slug'
      path: '/experiencias/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/experiencias/nova': {
      id: '/admin/experiencias/nova'
      path: '/nova'
      fullPath: '/admin/experiencias/nova'
      preLoaderRoute: typeof AdminExperienciasNovaRouteImport
      parentRoute: typeof AdminExperienciasRoute
    }
  }
}

interface AdminExperienciasRouteChildren {
  AdminExperienciasNovaRoute: typeof AdminExperienciasNovaRoute
}

const AdminExperienciasRouteChildren: AdminExperienciasRouteChildren = {
  AdminExperienciasNovaRoute: AdminExperienciasNovaRoute,
}

const AdminExperienciasRouteWithChildren =
  AdminExperienciasRoute._addFileChildren(AdminExperienciasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminExperienciasRoute: AdminExperienciasRouteWithChildren,
  ExperienciasSlugRoute: ExperienciasSlugRoute,
  ExperienciasIndexRoute: ExperienciasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
